##############################################################################
# COPYRIGHT(C)	: Samsung Electronics Co.Ltd, 2006-2011 ALL RIGHTS RESERVED
#                 Makefile for ISDB-T for NMI Driver
##############################################################################
# VERSION&DATE	: Version 0.1
##############################################################################

obj-$(CONFIG_ISDBT_FC8100)	+= fc8100.o bbm.o fc8100_bb.o fci_tun.o fci_hal.o fci_i2c.o fc8100_isr.o fc8100_tun.o fc8100_i2c.o fci_oal.o


EXTRA_CFLAGS += -Idrivers/media/video
